# Workflow de Integração Contínua (CI)
# Objetivo: executar os testes unitários da aplicação a cada push na branch main.
# Estrutura preparada para futuras expansões, mantendo um único job.

name: Continuous Integration

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '24'
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_SCOPE: livia-anjos

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Obtém o código-fonte do repositório
      - name: Checkout repository
        uses: actions/checkout@v6.1.0

      # Configura a versão do Node.js utilizada pelo projeto
      - name: Setup Node.js
        uses: actions/setup-node@v6.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Habilita o Corepack para gerenciamento do Yarn
      - name: Enable Corepack
        run: corepack enable

      # Instala as dependências do projeto
      - name: Install dependencies
        run: yarn install

      # Executa os testes unitários
      - name: Run unit tests
        run: yarn test
  
  build-and-deploy:
    name: Build $ Deploy Vercel Peview
    needs: [unit-tests]
    runs-on: ubuntu-latest

    
    steps:
      # Obtém o código-fonte do repositório
      - name: Checkout repository
        uses: actions/checkout@v6.1.0

      # Configura a versão do Node.js utilizada pelo projeto
      - name: Setup Node.js
        uses: actions/setup-node@v6.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Habilita o Corepack para gerenciamento do Yarn
      - name: Enable Corepack
        run: corepack enable

      # Instala as dependências do projeto
      - name: Install dependencies
        run: yarn install

      # Build para o Vercel
      - name: Build Vercel
        run: yarn vercel build --token=$VERCEL_TOKEN

      # Deploy preview no vercel
      - name: Deploy preview
        run: yarn vercel deploy --prebuilt --target=preview --token=$VERCEL_TOKEN --scope=$VERCEL_SCOPE

      
